language: c
install: bash -e .travis-ci-install.sh
script: bash -e .travis-ci.sh
cache: apt
matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.2
  - os: linux
    env: OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.2
  - os: linux
    env: OCAML_VERSION=4.00.1 OPAM_VERSION=1.2.2
  - os: linux
    env: OCAML_VERSION=3.12.1 OPAM_VERSION=1.2.2
  - os: linux
    env: OCAML_VERSION=4.03.0 OPAM_VERSION=1.2.2
  - os: linux
    env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0
  - os: linux
    env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.1.1
  - os: osx
    env: OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.2
  allow_failures:
  - os: osx
notifications:
  email:
  - opam-commits@lists.ocaml.org
  irc:
  - chat.freenode.net#opam
